const psaumes_invitatoire = {
  "23" : "<p><span class=\"verse_number\">1</span> Au Seigneur, le m<u>o</u>nde et sa richesse,<br>la terre et to<u>u</u>s ses habitants !<br><span class=\"verse_number\">2</span> C'est lui qui l'a fond<u>é</u>e sur les mers<br>et la garde inébranl<u>a</u>ble sur les flots.<br><br><span class=\"verse_number\">3</span> Qui peut gravir la mont<u>a</u>gne du Seigneur<br>et se ten<u>i</u>r dans le lieu saint ?<br><span class=\"verse_number\">4</span> L'homme au cœur pur, aux m<u>a</u>ins innocentes,<br>qui ne livre pas son <u>â</u>me aux idoles<br>&nbsp;&nbsp; (et ne dit p<u>a</u>s de faux serments).<br><br><span class=\"verse_number\">5</span> Il obtient, du Seigne<u>u</u>r, la bénédiction,<br>et de Dieu son Sauve<u>u</u>r, la justice.<br><span class=\"verse_number\">6</span> Voici le peuple de ce<u>u</u>x qui le cherchent !<br>Voici Jacob qui rech<u>e</u>rche ta face !<br><br><span class=\"verse_number\">7</span> Portes, lev<u>e</u>z vos frontons, +<br>élevez-vous, p<u>o</u>rtes éternelles :<br>qu'il entre, le r<u>o</u>i de gloire!<br><br><span class=\"verse_number\">8</span> Qui est ce r<u>o</u>i de gloire ? +<br>C'est le Seigneur, le f<u>o</u>rt, le vaillant,<br>le Seigneur, le vaill<u>a</u>nt des combats.<br><br><span class=\"verse_number\">9</span> Portes, lev<u>e</u>z vos frontons, +<br>levez-les, p<u>o</u>rtes éternelles :<br>qu'il entre, le r<u>o</u>i de gloire !<br><br><span class=\"verse_number\">10</span> Qui donc est ce r<u>o</u>i de gloire ? +<br>C'est le Seigneur, Die<u>u</u> de l'univers ;<br>c'est lui, le r<u>o</u>i de gloire.</p>",
  "66" : "<span class=\"verse_number\">2</span> Que Dieu nous prenne en gr<u>â</u>ce et nous bénisse,<br>que son visage s’illum<u>i</u>ne pour nous ;<br><span class=\"verse_number\">3</span> et ton chemin sera conn<u>u</u> sur la terre,<br>ton salut, parmi to<u>u</u>tes les nations.<br><br><span class=\"verse_number\">R/ 4</span> Que les peuples, Die<u>u</u>, te rendent grâce ;<br>qu’ils te rendent gr<u>â</u>ce tous ensemble !<br><br><span class=\"verse_number\">5</span> Que les nations ch<u>a</u>ntent leur joie,<br>car tu gouvernes le m<u>o</u>nde avec justice ;<br>tu gouvernes les pe<u>u</u>ples avec droiture,<br>sur la terre, tu condu<u>i</u>s les nations.<br><br><span class=\"verse_number\">R/ 6</span> Que les peuples, Die<u>u</u>, te rendent grâce ;<br>qu’ils te rendent gr<u>â</u>ce tous ensemble !<br><br><span class=\"verse_number\">7</span> La terre a donn<u>é</u> son fruit ;<br>Dieu, notre Die<u>u</u>, nous bénit.<br><span class=\"verse_number\">8</span> Que Die<u>u</u> nous bénisse,<br>et que la terre tout enti<u>è</u>re l’adore !<br>",
  "94" : "<p><span class=\"verse_number\">1</span> Venez, crions de j<u>o</u>ie pour le Seigneur,<br />\nacclamons notre Roch<u>e</u>r, notre salut !<br /><span class=\"verse_number\">2</span> Allons jusqu'à lu<u>i</u> en rendant grâce,<br />\npar nos hymnes de f<u>ê</u>te acclamons-le !<br /><br /><span class=\"verse_number\">3</span> Oui, le grand Die<u>u</u>, c'est le Seigneur,<br />\nle grand roi au-dess<u>u</u>s de tous les dieux :<br /><span class=\"verse_number\">4</span> il tient en main les profonde<u>u</u>rs de la terre,<br />\net les sommets des mont<u>a</u>gnes sont à lui ;<br /><span class=\"verse_number\">5</span> à lui la mer, c'est lu<u>i</u> qui l'a faite,<br />\net les terres, car ses m<u>a</u>ins les ont pétries.<br /><br /><span class=\"verse_number\">6</span> Entrez, inclinez-vo<u>u</u>s, prosternez-vous,<br />\nadorons le Seigne<u>u</u>r qui nous a faits.<br /><span class=\"verse_number\">7</span> Oui, il <u>e</u>st notre Dieu ; +<br />\nnous sommes le pe<u>u</u>ple qu'il conduit,<br />\nle troupeau guid<u>é</u> par sa main.<br /><br />\nAujourd'hui écouterez-vo<u>u</u>s sa parole ? +<br /><span class=\"verse_number\">8</span> « Ne fermez pas votre cœ<u>u</u>r comme au désert,<br />\ncomme au jour de tentati<u>o</u>n et de défi,<br /><span class=\"verse_number\">9</span> où vos pères m'ont tent<u>é</u> et provoqué,<br />\net pourtant ils avaient v<u>u</u> mon exploit.<br /><br /><span class=\"verse_number\">10</span> « Quarante ans leur générati<u>o</u>n m'a déçu, +<br />\net j'ai dit : Ce peuple a le cœ<u>u</u>r égaré,<br />\nil n'a pas conn<u>u</u> mes chemins.<br /><span class=\"verse_number\">11</span> Dans ma colère, j'en ai f<u>a</u>it le serment :<br />\nJamais ils n'entrer<u>o</u>nt dans mon repos. »</p>",
  "99" : "<span class=\"verse_number\">1</span> Acclamez le Seigne<u>u</u>r, terre entière,<br><span class=\"verse_number\">2</span> servez le Seigne<u>u</u>r dans l'allégresse,<br>venez à lui avec des ch<u>a</u>nts de joie ! <br><br><span class=\"verse_number\">3</span> Reconnaissez que le Seigne<u>u</u>r est Dieu :<br>il nous a faits, et nous s<u>o</u>mmes à lui,<br>nous, son pe<u>u</u>ple, son troupeau. <br><br><span class=\"verse_number\">4</span> Venez dans sa mais<u>o</u>n lui rendre grâce,<br>dans sa demeure chant<u>e</u>r ses louanges ;<br>rendez-lui grâce et béniss<u>e</u>z son nom !<br><br><span class=\"verse_number\">5</span> Oui, le Seigne<u>u</u>r est bon,<br>étern<u>e</u>l est son amour,<br>sa fidélité deme<u>u</u>re d'âge en âge.<br>"
}

function psaume_invitatoire_from_reference(psaume_index){
  let psaume = psaumes_invitatoire[psaume_index];
  return (psaume == undefined) ? "" : psaume
}
